In [1]:
pip install scikit-learn==0.24.2 

Note: you may need to restart the kernel to use updated packages.


'E:\Geeta' is not recognized as an internal or external command,
operable program or batch file.


In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

In [8]:
x = np.arange(1,25).reshape(12,2) 
y = np.array([0,1,1,0,1,0,0,1,1,0,1,0])


In [4]:
x

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [9]:
y

array([0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0])

In [11]:
#Applying the train test model 
x_train, x_test, y_train, y_test = train_test_split(x,y)

In [12]:
x_train

array([[ 1,  2],
       [21, 22],
       [13, 14],
       [ 9, 10],
       [ 3,  4],
       [15, 16],
       [23, 24],
       [11, 12],
       [ 7,  8]])

In [13]:
x_test

array([[17, 18],
       [19, 20],
       [ 5,  6]])

In [14]:
y_train

array([0, 1, 0, 1, 1, 1, 0, 0, 0])

In [15]:
y_test

array([1, 0, 1])